version: '3.9'

services:
  # DATABASE - POSTGRESQL
  db:
    container_name: dbpostgreSQL
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    # networks:
    #   - app
    volumes:
      - pg-data:/var/lib/postgresql/data
  #Development
#   api-dev:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     working_dir: /app
#     networks:
#       - app

# networks:
#   app:

volumes:
  pg-data: {} # PERSISTENT VOLUME POSTGRESQL - DB
