version: '3.9'

services:
  # DATABASE - POSTGRESQL
  db-postgres:
    container_name: dbpostgreSQL
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app 
    restart: always
    ports:
      - 5432:5432
    networks:
      - app
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app 
    ports:
      - 3000:3000
    depends_on:
      - db-postgres 
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks: 
  app:

# volumes:
#    pg-data: {} # PERSISTENT VOLUME POSTGRESQL - DB
